### PR TITLE
Recover from bad zk connections

### LINKED ISSUE #92: ZK connectivity failure with multiple watchers leads to permanent failure
**Setup**:
6 nerve service watchers on the same instance connected to the same ZK pool

**How to reproduce**:
1. The instance has a problem connecting to ZK
2. Nerve -> 
`Nerve::Nerve: nerve: watcher service1 not alive; reaping and relaunching`
`Nerve::ServiceWatcher: nerve: stopping service watch service1`
`Nerve::Nerve: nerve: could not reap service1, got #<Zookeeper::Exceptions::NotConnected: Zookeeper::Exceptions::NotConnected>`
3. This continues in a loop for each service watcher until nerve is restarted.  

**Actual problem**:
The problem is that in start() in zookeeper.rb there are no checks to see if the ZK connection is alive before re-using in.

### PR DESCRIPTION
**Pull request by jolynch**
Should fix #92 

I think that we might need to somehow touch zk in zk_delete for this to really work, but WIP.

### CODE REVIEW

**Comment by minkovich** [comment]
@jolynch could you merge this? We just had this issue reoccur.

**Comment by EdwoodTyler** [comment]
Hello! No, i couldn't merge this

**Comment by jolynch** [comment]
@minkovich yea let me dig this back up, I'll try to get this merged this week.

**Comment by panchr** [comment]
Closing because already fixed in #113.

**Pull request closed without merging**
